### ISSUE TITLE
Avoid bundling the Guzzle HTTP library

### ISSUE THREAD

**Issue by nicodemuz** [paytrail/paytrail-php-sdk#9]
It would be great if you could choose a HTTP client of your own choosing and avoid bundling with Guzzle as done in:
https://github.com/paytrail/paytrail-php-sdk/tree/master/lib/guzzlehttp

Consider interfacing with Symfony contracts or PSR-18:
https://symfony.com/doc/current/http_client.html#interoperability

**Comment by EreMaijala** [comment]
Or at least make it so that Guzzle isn't created in the constructor or used anywhere else than in the post method. Currently the post method takes a Uri as parameter, which makes it dependent on Guzzle, and I can't see any reason why it couldn't be a simple string instead. This would allow a subclass to just override the post method.
